### PR TITLE
Add extra properties for userProfile

### PR DESCRIPTION
**Pull request by vedi**

### CODE REVIEW

**Comment by refaelos** [comment]
Do we still need this PR ?

**Comment by vedi** [comment]
@refaelos, it solves this issue: http://answers.soom.la/t/facebook-access-token/2772

but it's very-very old.

**Comment by refaelos** [comment]
Yes. This is a good idea to have this but it'll also need to be reflected in android/unity/cocos2dx

**Comment by vedi** [comment]
We had PR for ios, android, and cocos2d-x. Just seen another topic about this: http://answers.soom.la/t/how-to-get-session-token-upon-successful-login/2813

I'll create a ticket.

**Comment by refaelos** [comment]
so you're replacing this PR? Can we close it?

**Comment by vedi** [comment]
yep, we'll have another one:
https://github.com/soomla/ios-profile/pull/14

**Pull request closed without merging**
